---
id:         bootloader_selection
name:       "Choose your Bootloader"
# Change to 'radio' so it doesn't automatically install the packages
method:     radio
default:    grub

items:
  - id: grub
    name: "GRUB"
  - id: systemd-boot
    name: "systemd-boot"
  - id: refind
    name: "rEFInd"
