---
i18n:
    name: "Installing Selected Bootloader"

dontChroot: false
timeout: 300

script:
    # --- GRUB ---
    - command: "pacman -S --noconfirm grub efibootmgr && grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Arch && grub-mkconfig -o /boot/grub/grub.cfg"
      chroot: true
      condition: "global.packagechooser_bootloader_selection == 'grub'"

    # --- SYSTEMD-BOOT ---
    - command: "bootctl install"
      chroot: true
      condition: "global.packagechooser_bootloader_selection == 'systemd-boot'"

    # --- REFIND ---
    - command: "pacman -S --noconfirm refind efibootmgr && refind-install --yes"
      chroot: true
      condition: "global.packagechooser_bootloader_selection == 'refind'"
