---
dontChroot: false
timeout: 600
name: "Installing selected bootloader"

script:
    # Logic for GRUB
    - command: "[ \"$package_bootloader_selection\" = \"grub\" ] && pacman -S --noconfirm grub efibootmgr && grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=HyprArch && grub-mkconfig -o /boot/grub/grub.cfg"
    
    # Logic for systemd-boot
    - command: "[ \"$package_bootloader_selection\" = \"systemd-boot\" ] && bootctl install"
    
    # Logic for rEFInd
    - command: "[ \"$package_bootloader_selection\" = \"refind\" ] && pacman -S --noconfirm refind && refind-install"
